### ISSUE TITLE
Should not list available panes within a global dashboard pane

### ISSUE THREAD

**Issue by megoth** [SolidOS/solid-panes#142]
In the latest version of the data browser we've introduced global dashboards. These reuse parts of the outline manager that also reuses the listing of panes available. This list is probably just confusing in this version, and I propose that we remove this list from the global dashboard panes.

![AwesomeScreenshot-megoth-dev-inrupt-net--2019-08-12_1_54](https://user-images.githubusercontent.com/775139/62863308-b379c200-bd08-11e9-9a8f-4a486bc6f763.png)

**Comment by Vinnl** [comment]
@timbl What do you think is the best way to detect whether the OutlineManager is rendering inside the dashboard?

**Comment by Vinnl** [comment]
This issue was deprioritised since there was not a clear way to do this: removing the call to `renderPaneIconTray` when `options.pane.global` is `true` in `expandedHeaderTR` did remove that list, but it also caused the Pane not to get displayed at all. Since Tim did not consider this Issue that important, we're postponing it for now.

Of course, PRs still welcome if anybody else wants to pick this up :)

**Comment by timbl** [comment]
Suggest setting the CSS visibility of the header TR to hidden, but leaving the structure of the DOM
 visibility: hidden;

**Comment by timbl** [comment]
It isn't about the outline manager rendering inside the dashboard. It oi=is about the outline manager rendering a global pane, not a view pane.

**Comment by megoth** [comment]
This was fixed in https://github.com/solid/solid-panes/pull/153
