### ISSUE TITLE
Consolidate main.css and tabbedtab.css into one file: mash.css

### ISSUE THREAD

**Issue by megoth** [SolidOS/solid-panes#149]
Right now we are creating a local file and loading one externally, using GitHub as a CDN. This may create bugs as the "GitHub as CDN" doesn't handle versioning really way (as evidenced by the latest version of inrupt.net and solid.community).

We should consolidate both of these into one local file that is created by mashlib.

Tim also wants us to phase these global CSS out altogether in the future.

**Comment by mikeadams1** [comment]
> Right now we are creating a local file and loading one externally, using GitHub as a CDN. This may create bugs as the "GitHub as CDN" doesn't handle versioning really way (as evidenced by the latest version of inrupt.net and solid.community).

What bugs are you talking about, there is nothing here that indicates a certain bug will be fixed by this.

**Comment by mikeadams1** [comment]
I do not agree that these two files should be merged into one file.

**Comment by megoth** [comment]
And for what reason should we maintain these two sources instead of one single one that makes for less risk to create bugs?

**Comment by Vinnl** [comment]
> What bugs are you talking about, there is nothing here that indicates a certain bug will be fixed by this.

Good point, it's good to publicly log these bugs.

So the bug is that whenever a new version of mashlib gets pushed to GitHub, it is automatically deployed to the currently hardcoded URL. That means that every deployment of mashlib would automatically get that new version, even if its DOM structure had not yet been updated to align with the changes in the CSS.

Additionally, making requests to third parties (GitHub, in this case), is also an anti-feature for a privacy-focused project like Solid.

Note that in #50, the CSS files are still two separate sources. They are only bundled into a single on for distribution to the user, to minimise the number of HTTP requests that need to be made, and thus improve performance.

As an aside, to support @megoth's question: I think it's generally a good idea to not just say "I do not agree", but also to explain why not - that makes it easier to weigh the advantages and disadvantages.

**Comment by mikeadams1** [comment]
@megoth I am not trying to be disagreeable, I just did not understand the reasoning behind this decision, and when your say that;

> This may create bugs as the "GitHub as CDN" doesn't handle versioning really way (as evidenced by the latest version of inrupt.net and solid.community).

I was not understanding what bugs you were referring to because you did not mention any specifically that have, or could occur, nor any mention of any potential fallout that could arise because of this change, who will be affected, what effect will this have on apps using the current state etc.

@Vinnl again, not trying to be disagreeable here at all, I am trying to understand what effect this will have pro and con on both sides of the coin. If we leave it the way it is, X,Y, and Z can happen, once we change it, it is less likely to happen but, may cause A and B but, we will deal with that as needed sort of thing.

I was only wondering, what does this fix, prevent, and what is the downside. There was nothing stated.

**Comment by Vinnl** [comment]
Well, you did explicitly say you did not agree :) But wanting to understand the reasoning is a fair point, so: did my comment above sufficiently address that?

**Comment by mikeadams1** [comment]
Not really because, there was no for instance, and I was not to far off your not understanding https://github.com/solid/solid-panes/issues/144#issuecomment-520737156 and was just looking for some clarification on this, what will be different, what will be affected and to be transparent, there appeared to be a lack of documentation as to why this was being done in the first place. If the reasoning is because @timbl says so, no disrespect intended, who will ever know the reasons why this change was done. So I would suggest that in the future we make it more clearly understandable for those who come after us, why this change was done.

So, what or who will be affected by consolidating?

**Comment by Vinnl** [comment]
Note that #144 has no relation whatsoever to this Issue.

The reasoning behind this change is what I said earlier:

> So the bug is that whenever a new version of mashlib gets pushed to GitHub, it is automatically deployed to the currently hardcoded URL. That means that every deployment of mashlib would automatically get that new version, even if its DOM structure had not yet been updated to align with the changes in the CSS.
> 
> Additionally, making requests to third parties (GitHub, in this case), is also an anti-feature for a privacy-focused project like Solid.

Nobody should be affected specifically, other than not encountering broken styles in the future caused by that issue, and no longer being able to theoretically be tracked by GitHub when using the data browser.

Does that make sense?

**Comment by mikeadams1** [comment]
> Note that #144 has no relation whatsoever to this Issue.

I was trying to show you that in #144 you were uncertain about a matter, in that issue, and you needed clarification, timbl responded by clarifying what it was you did not understand.

I was seeking the same thing in general that you were, some clarification with specificity, absent, understanding the reasoning, then I do not agree. So what specifically will this consolidation do that may have a negative impact such as, how will the data browser work differently, and does this have any effect on the data browser as aweb app?

If I am uncertain about the cause and effect of something your doing, I will ask, maybe I could have been more specific, and for that my apologies. Currently, I can use the data browser as a web app, I have it running on github.io, however, that is currently running with mashilb.js hack because the dist was removed from a previous version rendering it broken. I would prefer to have it work using solid code but, someone decided in the middle of the night to break it. So again, by consolidating the main.css and the tabbedtab.css into one file, break anything at all?

**Comment by Vinnl** [comment]
> I was seeking the same thing in general that you were, some clarification with specificity, absent, understanding the reasoning, then I do not agree. 

Ah, I understand, thanks for clarifying.

> So what specifically will this consolidation do that may have a negative impact such as, how will the data browser work differently, and does this have any effect on the data browser as aweb app?

As I said before:

> Nobody should be affected specifically, other than not encountering broken styles in the future caused by that issue, and no longer being able to theoretically be tracked by GitHub when using the data browser.

Is there anything in there that's unclear?

> Currently, I can use the data browser as a web app, I have it running on github.io, however, that is currently running with mashilb.js hack because the dist was removed from a previous version rendering it broken.

Ah, I wasn't aware that you were doing that, thanks for clarifying. Does that work at all? How does it know which Pod to connect to?

In any case, if that _did_ work, as far as I can tell this change should only make that easier: you can build the code, and serve all the assets yourself. That way, it can no longer break in the middle of the night because of changes made elsewhere :)

**Comment by mikeadams1** [comment]
> Ah, I wasn't aware that you were doing that, thanks for clarifying. Does that work at all? How does it know which Pod to connect to?

You can view it here: https://github.com/mikeadams1/form-playground the code I am using is here: https://solid.github.io/solid-panes/style/tabbedtab.css
https://mikeadams1.github.io/form-playground/mashlib.js

I am also working on a solid-cam, https://index.solid.community/public/camera/solid-cam.html that was working just fine yesterday and is broke today, so now I have to chase down what it is you all have done to the code so that I can fix it and make it work again. To be blunt, if all your going to do is chase me around and change the code so that things I am working on break, then I have the obligation to ask why you are now consolidating here and why is it that all of your changes effect the apps I am working on?

Does this answer your questions?

**Comment by mikeadams1** [comment]
> you can build the code, and serve all the assets yourself. That way, it can no longer break in the middle of the night because of changes made elsewhere :)

I should be able to rely on the solid/ code. Are you saying that the Solid code is unreliable?

**Comment by Vinnl** [comment]
Ah I see, that's pretty cool. Yes, that answers my questions.

So then again, I think you'll really benefit from this change, although it does require you to update your fork as well. Because your code is directly pulling whatever we push to `solid.github.io` directly [here](https://github.com/mikeadams1/form-playground/blob/master/index.html#L6), it can break whenever we make a change. If, instead, you now copy the `mash.css` that will be generated here after this change, into your own repository, then it will no longer break when we make a change.

(While I posted this you asked whether I said the Solid code is unreliable. My answer would be: when we commit to a public, documented API, you should be able to rely on that. However, like all code bases: the implementation behind that API does change, yes, so the only reliable way to depend on every line of code being in a particular state, is to fork it. Which you've done with the rest of the code, which is great! Now you'll be able to do lock down the CSS as well.)

**Comment by mikeadams1** [comment]
If the css you want me to lock down renders my work broken, why would I want to agree to it? You broke it, and if you cant provide me a path to fix it, then why would I want to agree to this consolidation? Like I said, if all your going to do is chase me around with the intent to break what it is I am working on personally, then I do not agree to the changes being made herein.

If you have a problem with my implementation, and use of the code as I am utilizing it, just say so and we can come to some terms, but to isolate me personally and the apps I am working on, which is clearly the documented case here, then I do not agree to these or other changes aforementioned and forthwith.

**Comment by mikeadams1** [comment]
So now that its all on the table, what say you.) Is timbl upset that I am using his code? and this is a way to isolate it and render it useless? Was the code he was using previously on the aforementioned secret? @timbl @megoth @Vinnl

**Comment by mikeadams1** [comment]
Look, I am a high school dropout, never made it past the 10th grade so, if there is something I am not understanding, maybe you can enlighten me.

**Comment by Vinnl** [comment]
> If the css you want me to lock down renders my work broken, why would I want to agree to it? You broke it, and if you cant provide me a path to fix it, then why would I want to agree to this consolidation?

You don't necessarily need to lock down the CSS introduced in _this commit_: feel free to fork the version in an earlier commit and copy that over into your repository. In fact, I'd recommend that.

> Like I said, if all your going to do is chase me around with the intent to break what it is I am working on personally, then I do not agree to the changes being made herein.

Please try to assume good intentions when interacting with people. The intent is absolutely not to break the things you are working on personally; the problem is that we cannot predict what is going to break for you, because there is no stable public API that you are relying on. Forking the CSS here would solve that issue.

> If you have a problem with my implementation

I don't; I think it's great and kind of amazing that you got it to work in the first place.

> to isolate me personally and the apps I am working on, which is clearly the documented case here

As mentioned above: I find that it is more pleasant to assume good intentions when interacting online, and would appreciate it if you would try to do so. All this is open source, explicitly so that you can take the code and do with it what you want.

Ah, and something to keep in mind: it might sometimes take a while for at least me to respond, because I'm also working on other things. Not saying that this is a problem now, but I'm being pre-emptive here :)

**Comment by mikeadams1** [comment]
> Ah, and something to keep in mind: it might sometimes take a while for at least me to respond, because I'm also working on other things. Not saying that this is a problem now, but I'm being pre-emptive here :)

agreed

My apologies, I am not trying to receive you with doubtful disputations, my observations are as I see them.

**Comment by mikeadams1** [comment]
I agree to consolidate in hopes that this will fix what it is you are all trying to do, I will get my apps working on my own. At some point you all may want to pay proper attributes regarding some of these changes due to mikeadams1 hacking the code. If I have done something that your all not to specifically fond of, and your going to delete dist, and change and consolidate because of something I have done, maybe you should @mention it. If I have used the code, and insodoing exposed a weakness that was not foreseen by the team, you should at the very least @mention it.

**Comment by mikeadams1** [comment]
I got the camera code from timbl, here: https://timbl.com/timbl/Public/Test/2018/Camera/cameraCapture.html

It was working on his pod yesterday, here is proof. https://timbl.com/timbl/Public/Test/2018/Camera/img1565805891000.png

Now, today his is not working and neither is mine, is that a coincident?

**Comment by megoth** [comment]
As @Vinnl has mentioned, you cannot rely on the code that's served via GitHub Pages. There is no promise from our team to keep that maintained or supporting a specific set of features that is needed in projects that at a specific iteration started using the code and relies on features in that iteration.

The code and features are available on GitHub and through packages on NPM. Choose the one you need, and if necessary, do the changes you need. (But I don't recommend monkey-patching code that you depend on via NPM.)

I suggest you fork the projects you need and maintain it to your need. Doing that, you can keep it up to date with our work, but remove the parts you don't like or need, e.g. by reverting commits or simply change the parts you don't need and create commits off your own.

If you have some change that you think are usable to original code, you can also create a PR with those changes.

If you haven't already, I suggest you read [Fork a repo](https://help.github.com/en/articles/fork-a-repo) and fork the repos you need (solid-panes for tabbedtab.css) and build it like you need it.

**Comment by mikeadams1** [comment]
Great, I thought you were all building it and we could rely on it as we need it but, I may have been misunderstanding that entirely. I think I understand now that you are building it as you need it, not necessarily in our interests but, if your changes breaks anything we are working on siamotainously it is our fault? Well like I said, I only have a 10th grade education so forgive me if I have not understood these points you are commenting on.

**Comment by megoth** [comment]
We have given you the path to resolve your problems, and stated our reasons for continuing this path of development. AFAIAC this issue is resolved, and we'll merge https://github.com/solid/mashlib/pull/50 if @timbl accepts it.

**Comment by mikeadams1** [comment]
I already stated that I agree to it, 

> I agree to consolidate

Merge away!

**Comment by mikeadams1** [comment]
> We have given you the path to resolve your problems

These are not problems, ^^ they are issues!

**Comment by timbl** [comment]
Hold on.  While making different better systems for generating the CSS is a good idea, it is also important that old files in the GitHub.io service are maintained. So the old CSS and JS and HTML files must be preserved. They are used by all kinds of people.

**Comment by megoth** [comment]
Then we need to state this explicitly somewhere. I'm a fan of COOL URIs and all, but maintaining the content of CSS such that we promise to not break the use of specific CSS classes are going to create an extra layer of maintenance for us.

**Comment by mikeadams1** [comment]
I don't know if I can help with maintaining some of these files but, I would be happy to do so, at your direction. I have started compiling my own files in various repos as you suggested.

**Comment by megoth** [comment]
This was fixed in https://github.com/solid/mashlib/pull/50.

Note that some of the resources that were identified as part of the discussion here were reintroduced through https://github.com/solid/mashlib/issues/57.
