### ISSUE TITLE
Allow either default or non-default export in pane API

### ISSUE THREAD

**Issue by timbl** [SolidOS/solid-panes#159]
The TS-based pane building world has been made more complex by the need to import psnaes written with `module.exports = x`, and panes written with ` export default x`.

Suppse the function which registers a p[ane accepts either style.

And we document that

Like

```
   register(p)
    p = p.default || p
   ...
```

**Comment by Vinnl** [comment]
I'd even prefer not using the default export, but exporting a constant called e.g. `pane`.

Also note that we don't _need_ to use ES modules with TypeScript - it was a somewhat arbitrary choice made during the migration. If we do decide to go ahead with them, though, I propose that we change _all_ Pane definition files to use ES modules, rather than making a function that deals with either style - plain Babel should support them as well, and changing them all over should take about 15 minutes, I'd guess. (Well, apart from the ones that are published in separate repositories in separate packages, but that too should be manageable.)

**Comment by megoth** [comment]
This has been fixed with https://github.com/solid/solid-panes/pull/202
