### ISSUE TITLE
Resources disappears when expanding in browser

### ISSUE THREAD

**Issue by jholleran** [SolidOS/solid-panes#185]
URL: https://team.inrupt.net/public/lit/

When I'm *not* logged in I am able to view and expand the 'vocab' container:
![image](https://user-images.githubusercontent.com/1751613/66383050-34290780-e9b4-11e9-9302-842f8317710b.png)

![image](https://user-images.githubusercontent.com/1751613/66382960-09d74a00-e9b4-11e9-997f-5686425abf22.png)

When I'm logged in I can view the container but when I try to expand it the directory disapears:
![image](https://user-images.githubusercontent.com/1751613/66383093-4acf5e80-e9b4-11e9-8623-0f0892cbc6d6.png)

The same issue is happening for files. 

I can get to the resource but I need to supply the full URL (For example; https://team.inrupt.net/public/lit/vocab/)

Is this a known issue?

**Comment by brownhoward** [comment]
The issue is not known to me. Tried replicating but could not. I could access and view the core.ttl when logged in (Safari browser) or logged in (Chrome browser):
![Screen Shot 2019-10-08 at 07 59 26](https://user-images.githubusercontent.com/45850928/66394166-56b22500-e9a2-11e9-929c-5ba6d67f1ee9.png)

This is the same when I both navigate to the folder and type in the URL.

What browser are you using? And I'll ask the obvious question, have you cleared your cache?

**Comment by jholleran** [comment]
Chrome: Version 77.0.3865.90 (Official Build) (64-bit)
OS:Ubuntu 18.04.3 LTS

I cleared the cache and the issue still occurs.

**Comment by james-martin-jd** [comment]
I am seeing this same issue on a different pod (https://solidsdk.inrupt.net) using my pod for access (https://jmartin.inrupt.net). I also tried clearing my cache and logging back in, and even used Chrome incognito mode and saw the same issue. When I am not logged in I can browser folders, but when I log in to create new files the directories disappear (or turn into green lines in the UI) when I expand them.

OS: MacOS 10.14.16
Chrome:  77.0.3865.90 (Official Build) (64-bit)

I also saw the following error in the console:
```
fetcher.js:960 Uncaught (in promise) Error: Fetcher: <https://jmartin.inrupt.net/settings/prefs.ttl> Origin Unauthorized
    at A.failFetch (fetcher.js:960)
    at fetcher.js:1569
```

**Comment by InruptKelly** [comment]
I'm seeing the same bug as James. Not seeing an error message, though. Just resources disappearing and being replaced with a little green bar

MacOS 10.14.6
Brave Version 0.68.132 Chromium: 76.0.3809.132 (Official Build) (64-bit)

**Comment by brownhoward** [comment]
@InruptKelly What is the URL of the resource you are trying to access? In your Pod or shared Pod?

**Comment by InruptKelly** [comment]
on the shared pod. Resource is the folder https://team.inrupt.net/2019/

**Comment by megoth** [comment]
I'm looking into this now.

I think this is a bug that is caused by the latest version of data browser, where it tries to fetch your preferences to figure out which kind of User Types you've assigned yourself with. But since it's another origin (team.inrupt.net VS [Your WebID]) it throws a 403.

I thought I've had thought of this when developing this feature, but obviously something that went wrong.

If you need to have this fixed ASAP, try to add https://team.inrupt.net as a trusted application in your profile - that should give the data browser access to your preferences.

I hope to have this fixed in a couple of hours, and we'll see how fast we can get it deployed.
