### ISSUE TITLE
Remove bloat from published package

### ISSUE THREAD

**Issue by angelo-v** [SolidOS/solid-panes#233]
There is a lot of unnecessary bloat in the published npm package as can be seen at https://unpkg.com/browse/solid-panes@3.1.4/

What is actually needed? `lib`, `dist`, or both? Anything else?

**Comment by michielbdejong** [comment]
I think one of them must be the module build, to be used in mashlib, and the other must be the webpack build, to be used as a stand-alone html app. Since mashlib already has the function of being an html app that includes solid-panes, I think we can probably remove the webpack build from solid-panes. Also because it takes several minutes (on my laptop) to build, I think it would make the solid-panes build much quicker if we only publish `lib` and just forget about `dist` altogether in this repo.

**Comment by bourgeoa** [comment]
dist was removed
