### ISSUE TITLE
Introduce TypeScript

### ISSUE THREAD

**Issue by megoth** [SolidOS/solid-panes#69]
As part of the work on the Solid data browser (that we mentioned in https://github.com/solid/solid-panes/issues/64 earlier) we want to introduce TypeScript to improve the code quality and making future refactoring of the code base easier. We will work on this in a separate branch until we know that it is stable enough and have consensus from the community.

[TypeScript](https://www.typescriptlang.org/) offers a variety of features that makes working with JavaScript easier. We suggest migrating code file by file as we improve the codebase, and making sure to enhance the new files with types where needed (ie set `noImplicitAny` to `true`).

We need to make sure that the build setup is rigid but flexible enough so that developers who do not want to use TypeScript for their work can opt out.

**Comment by gobengo** [comment]
@megoth In my experience a really good way to start introducing the type-checking benefits (e.g. for refactoring like you mention) without taking the potentially controversial (but IMO good) step of actually moving to the superset of the language is to take advantage of the fact that `tsc` can type-check JS files based on JSDoc comments.

I have used it in the past to add type-safety at time of continuous testing, but in a project where the owner wasn't sure about shifting languages. It worked quite well and caught many bugs that the team would have otherwise shipped to prod.

https://github.com/Microsoft/TypeScript/wiki/JSDoc-support-in-JavaScript

A slow-adoption with this as a milestone could also get merged back into master sooner and be a smaller [batch size](https://medium.com/the-agile-weekly/understanding-product-development-batch-size-work-in-process-wip-risk-for-small-teams-f551144ecbb5) of work, rather than maintaining a separate branch indefinitely, which can spiral out of control.

**Comment by megoth** [comment]
@gobengo thank you for your feedback. It is a good proposal, but we opted for moving files to TypeScript.

The code has been merged into the branch https://github.com/solid/solid-panes/tree/revamp, but we hope to merge that into master soon. We just need to resolve some questions with Tim first.
