### ISSUE TITLE
FolderPane is not refreshed properly after deleting a resource

### ISSUE THREAD

**Issue by megoth** [SolidOS/solid-panes#71]

**Comment by Vinnl** [comment]
I think this could theoretically be resolved by adding a change listener (e.g. `kb.updater.addDownstreamChangeListener`) for every object in a folder. node-solid-ws should send a notification through WebSockets that a file has been deleted, but after debugging it a bit with @michielbdejong, it appears that that does not work due to the following bug: https://github.com/solid/node-solid-ws/issues/4

Thus, I think this issue is blocked by that one.

**Comment by timbl** [comment]
Surely the folder pane only has to listen to changes in the folder resource itself, not all the children?

**Comment by timea-solid** [comment]
Deleting a resource is triggered in the internal-pane part of solid-panes, which in turn should affect the display of the immediate, parent folder, displayed in the folder-pane. So only the div of that resource has to be rerendered, which is part of the folder-pane.

**Comment by timbl** [comment]
In this bug, how was the resource deleted?   Using the internals pane, as the folder pane itself does not have a delete function.  Assume something out of the pane itself.   So we have to listen for a change.

**Comment by timbl** [comment]
Fixed by https://github.com/solid/folder-pane/pull/23
