### ISSUE TITLE
Introduce testing

### ISSUE THREAD

**Issue by megoth** [SolidOS/solid-panes#73]
We need to find a way to introduce tests in the current codebase. This will probably involve finding some sensible ways of separating some code into specific concerns, to figure out what is sensible to test and what is not (e.g. certain DOM manipulations might not be sensible to test).

This work item is heavily related to the work item [Implement conventions that facilitate separation of concern for panes](https://github.com/solid/solid-panes/issues/72), and one should not be done without considering the effects it will have on the other.

As pointed out in https://github.com/solid/solid-panes/pull/68#issuecomment-489916216 we should have a test for the trustedApp logic to make sure that there is no regression on the functionality. I think this is a good pane to start writing tests for.

**Comment by angelo-v** [comment]
Install a test library, e.g. jest, and start writing tests for newly introduced functionallity and bugs that are found. If something is hard to test, refactor so that the aspect under focus is separated and testable. Worst thing that could happen is an academic discussion about that instead of actually writing tests. Just start to test the things that are touched anyway.

**Comment by megoth** [comment]
Testing has been introduced into https://github.com/solid/solid-panes/tree/revamp, will merge that branch into master when we have resolved some issues with Tim.

Will close this issue for now, but introducing testing is an on-going issue and something we will do when working on various parts of Solid panes.
